[build]
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  DATABASE_URL = "postgresql://neondb_owner:npg_qN9lR1SAbJkT@ep-rough-fog-aeykznns-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
  ADMIN_KEY = "supersecretadminkey"
